---
sudo: required
env:
  - distro: centos8
language: python
services: []
before_install:
  - sudo dnf -y clean all
  - sudo dnf -y update 
install:
  - sudo dnf -y install git
  - python3 -m pip install 'molecule[docker]'
  # - python3 -m pip install required driver (e.g. docker, shade, boto, apache-libcloud)
script:
  - molecule test