---
sudo: required
env:
  - distro: centos8
language: python
services: []
before_install:
  - sudo apt-get -qq update 
install:
  - python3 -m venv ~/molecule
  - source ~/molecule/bin/activate
  - python3 -m pip install 'molecule[docker]'
  - python3 -m pip install --user "molecule[lint]"
  # - python3 -m pip install required driver (e.g. docker, shade, boto, apache-libcloud)
script:
  - molecule test