---

- name: Fix ownership of web root
  file:
    path: /var/www/html
    owner: apache
    group: oemrusers
    mode: 0775
  notify: restart apache

- name: Add oemruser user
  user:
    name: oemruser
    group: oemrusers

- name: Run composer install
  composer:
    command: install
    working_dir: "{{ web_document_root }}"

- name: Run npm install
  npm:
    path: "{{ web_document_root }}"
    global: no
    unsafe_perm: yes
  become: yes

- name: Run npm build
  command: /usr/bin/npm run build
    chdir: "{{ web_document_root }}"
    creates: "{{ web_document_root }}/public"

- name: Run composer autoload
  composer:
    command: dump-autoload
    optimize_autoloader: True
    working_dir: "{{ web_document_root }}"
