---

- name: Deploy autoconfigure php file
  template:
    src: auto_configure.php
    dest: /var/www/html/auto_configure.php 

- name: Fix ownership of web root
  file:
    path: /var/www/html
    owner: apache
    group: oemrusers
    recurse: yes

- name: Run autoconfiguration script
  command: "php auto_configure.php -f {{ openemr_auto_configuration }}"
  args:
    chdir: /var/www/html/
  when: autoconfigure is defined and autoconfigure
