---
- name: Start and enable firewalld
  systemd:
    name: firewalld
    state: started
    enabled: true

- name: Add http to the firewall
  firewalld:
    zone: public
    service: http
    permanent: yes
    state: enabled
    immediate: yes