---

- name: Deploy on RHEL 7
  include_tasks: rhel7.yml
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "7"

- name: Deploy on RHEL 8
  include_tasks: rhel8.yml
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "8"

- name: Deploy composer
  include_role:
    name: geerlingguy.composer

- name: Run composer and npm
  include_tasks: composer-install.yml

- name: Run auto configuration
  include_tasks: configure.yml
