---
- name: Install Dependencies
  yum:
    name:
      - "@MariaDB Database Client"
      - "@PHP Support"
      - "@Perl for Web"
      - "@Python"
      - firewalld
      - policycoreutils-python
    state: present
  when: node_type == "frontend"

- name: Install PHP 7.2 and httpd-24 from software collections
  yum:
    name:
      - rh-php72
      - rh-php72-php
    state: latest
  when: node_type == "frontend"

- name: Install Dependencies
  yum:
    name: 
      - "@MariaDB Database Server"
      - php-mysql
      - expect
      - MySQL-python
      - firewalld
      - policycoreutils-python
  when: node_type == "backend"

- name: Toggle httpd_unified selinux boolean
  seboolean:
    name: "{{ item }}"
    persistent: yes
    state: yes
  loop:
    - httpd_execmem 
    - httpd_unified
    - httpd_can_network_connect
  when: sestatus.stdout is defined and '"Enforcing" in sestatus.stdout'