---

# Handle the installation of Dependencies
- name: Disable EPEL
  yum_repository:
    name: epel
    state: absent

- name: Enable module streams
  dnf:
    name:
      - '@httpd:2.4'
      - '@nginx:1.14'
      - '@nodejs:10'
      - '@php:7.2'
    state: latest

- name: Install Dependencies
  dnf:
    name:
      - "php"
      - "php-mbstring"
      - "php-xml"
      - "nginx"
      - "php-fpm"
      - "php-json"
      - "php-cli"
      - "httpd"
      - "nodejs"
      - "php-mysqlnd"
      - "php-soap"
      - "php-gd"
      - "php-pecl-zip"
      - "php-ldap"
      - "wget"
      - "git"
      - "npm"
      - "firewalld"
      - "php-ldap"
      - "python3-libsemanage"
      - "sudo"
    state: latest

- name: Check if selinux is enabled
  command: getenforce
  register: sestatus
  changed_when: false
  failed_when: false

- name: Toggle httpd_unified selinux boolean
  seboolean:
    name: "{{ item }}"
    persistent: yes
    state: yes
  loop:
    - httpd_execmem 
    - httpd_unified
    - httpd_can_network_connect
  when: sestatus.stdout is defined and '"Enforcing" in sestatus.stdout'