---

# Handle the installation of Dependencies
- name: Enable module streams
  dnf:
    name:
      - '@httpd:2.4'
      - '@nginx:1.14'
      - '@nodejs:10'
      - '@php:7.2'
    state: latest

- name: Install Dependencies
  dnf:
    name:
      - "php"
      - "php-mbstring"
      - "php-xml"
      - "nginx"
      - "php-fpm"
      - "php-json"
      - "php-cli"
      - "httpd"
      - "nodejs"
      - "php-mysqlnd"
      - "php-soap"
      - "php-gd"
      - "php-pecl-zip"
      - "php-ldap"
      - "wget"
      - "git"
      - "npm"
      - "firewalld"
      - "php-ldap"
    state: latest

- name: Add oemrusers group
  group:
    name: oemrusers
    state: present

- name: Switch apache group to oemrusers
  lineinfile:
    regexp: "^Group apache"
    line: "Group oemrusers"
    path: "{{ apache_root }}/etc/httpd/conf/httpd.conf"
    state: present
  notify: restart apache

- name: Add DirectoryIndex index.php
  lineinfile:
    regexp: "    DirectoryIndex index.html"
    line: "    DirectoryIndex index.html index.php"
    path: "{{ apache_root }}/etc/httpd/conf/httpd.conf"
    state: present
  notify: restart apache

- name: Deploy phpinfo template
  template:
    src: phpinfo.php.j2
    dest: "{{ web_document_root }}/phpinfo.php"
  notify: restart apache

- name: Deploy php.ini template
  template:
    src: php.ini.j2
    dest: "{{ apache_root }}/etc/php.ini"
  notify: restart apache

- name: Download and unarchive OpenEMR release
  unarchive:
    src: "{{ download_openemr_link }}"
    dest: "{{ web_document_root }}"
    remote_src: yes
    extra_opts: [--strip-components=1]
    creates: /var/www/html/README.md
  notify: restart apache

- name: Start and enable apache
  systemd:
    name: "{{ httpd_service }}"
    state: started
    enabled: true

- name: Start and enable firewalld
  systemd:
    name: firewalld
    state: started
    enabled: true

- name: Add http to the firewall
  firewalld:
    zone: public
    service: http
    permanent: yes
    state: enabled
    immediate: yes

- name: Toggle httpd_unified selinux boolean
  seboolean:
    name: httpd_unified
    state: yes

- name: Chown /var/lib/php/session to root:oemrusers
  file:
    path: "{{ php_root }}/lib/php/session"
    owner: root
    group: oemrusers
  ignore_errors: true
