---
- name: Converge
  hosts: all
  vars:
    autoconfigure: 'true'
    mysql_host_fqdn: 'localhost'
    mysql_root_password: 
  roles:
  - name: "diodonfrost.mariadb"

  tasks:

  - name: Create a new database with name 'openemr'
    mysql_db:
      name: "{{ mysql_openemr_db_name }}"
      encoding: "{{ mysql_openemr_db_encoding }}"
      collation: "{{ mysql_openemr_db_collation }}"
      state: present

  - name: Create openemr database user
    mysql_user:
      name: "{{ mysql_openemr_user }}"
      password: "{{ mysql_openemr_user_password }}"
      encrypted: no
      priv: "{{ mysql_openemr_db_name }}.*:ALL"
      state: present

  - name: Testing openemr-ansible role
    import_role:
      name: "openemr-ansible"
    tags:
      - autoconfigure