---
dependency:
  name: galaxy
  options:
    role-file: molecule-requirements.yml
lint: |
  set -e
  yamllint .
driver:
  name: docker
platforms:
  # - name: ubi8
  #   image: registry.access.redhat.com/ubi8-init
  #   pre_build_image: true
  #   privileged: true
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   command: "/usr/sbin/init"
  #   exposed_ports:
  #     - 80
  #   published_ports:
  #     - 0.0.0.0:8080:80/tcp
  - name: centos8
    image: centos:8
    groups:
      - openemr
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: "/usr/sbin/init"
    exposed_ports:
      - 80
    network_mode: host
    published_ports:
      - 0.0.0.0:8081:80/tcp
  - name: mariadb
    image: mariadb:10.3
    groups:
      - database
    exposed_ports:
      - 3306
    network_mode: host
    published_ports:
      - 0.0.0.0:3306:3306/tcp
    env:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: openemr
      MYSQL_USER: openemr
      MYSQL_PASSWORD: 'example-password'
provisioner:
  name: ansible
verifier:
  name: ansible